// pages/orders/+page.svelte
<script>
	import TablesGrid from '$lib/components/layouts/TablesGrid.svelte';
	import PageContainer from '$lib/components/page-container/PageContainer.svelte';
	import Table from '$lib/components/table/Table.svelte';
	import { ORDERS_HEADER } from '../consts';

	import { mapTableFromDTO } from './utils';

	export let data;
	const tables = data.tables.map(mapTableFromDTO);
</script>

<PageContainer headerText={ORDERS_HEADER}>
	<TablesGrid>
		{#each tables as { id, shape }}
			<Table {id} {shape} />
		{/each}
	</TablesGrid>
</PageContainer>

// src/app/orders/page.tsx
import { mapTableFromDTO } from './utils';
import type { Table as TableType } from './types';
import { ORDERS_HEADER } from '../consts';

import { backofficeAPI } from '../../lib/backoffice/backofficeService';
import { TablesGrid } from '../../UI/layouts/TableGrid';
import { PageContainer } from '../../UI/page-container/PageConteiner';
import { Table } from '../../UI/table/Table';

export default async function OrdersPage() {
  const tablesDTO = await backofficeAPI.getTables();
  const tables: TableType[] = tablesDTO.map(mapTableFromDTO);

  return (
    <PageContainer headerText={ORDERS_HEADER}>
      <TablesGrid>
        {tables.map(({ id, shape }) => (
          <Table key={id} id={id} shape={shape} />
        ))}
      </TablesGrid>
    </PageContainer>
  );
}
