// pages/menu/+page.svelte
<script lang="ts">
	import Card from '$lib/components/card/Card.svelte';
	import MenuList from '$lib/components/menu-list/MenuList.svelte';
	import PageContainer from '$lib/components/page-container/PageContainer.svelte';
	import Header from '$lib/components/typography/Header.svelte';
	import { MENU_SUBHEADER, SELECTED_ITEMS_SUBHEADER } from './consts.js';
	import { mapItemFromDTO } from './utils.js';
	export let data;

	const menuItems = data.items.map(mapItemFromDTO);
</script>

<PageContainer>
	<div class="content-container">
		<div class="menu-container">
			<Card>
				<Header level={3} text={MENU_SUBHEADER} />
				<MenuList {menuItems}></MenuList>
			</Card>
		</div>
		<div class="selected-items">
			<Card><Header level={3} text={SELECTED_ITEMS_SUBHEADER} /></Card>
		</div>
	</div>
</PageContainer>

<style>
	.content-container {
		display: flex;
		justify-content: space-around;
		width: 100%;
	}

	.menu-container {
		width: 45%;
	}

	.selected-items {
		width: 45%;
	}
</style>

// src/routes/menu/Menu.tsx
import { MENU_SUBHEADER, SELECTED_ITEMS_SUBHEADER } from './consts';
import { mapItemFromDTO } from './utils';
import styles from './Menu.module.css';
import type { MenuItem } from './types';
import { Card } from '../../UI/cards/Card';
import { MenuList } from '../../UI/menu-list/MenuList';
import { PageContainer } from '../../UI/page-container/PageConteiner';
import { Header } from '../../UI/typography/Header';
import { useLoaderData } from 'react-router-dom';

export default function Menu() {
  const { itemsDTO } = useLoaderData();
  const menuItems: MenuItem[] = itemsDTO.map(mapItemFromDTO);

  return (
    <PageContainer>
      <div className={styles.contentContainer}>
        <div className={styles.menuContainer}>
          <Card>
            <Header level={3} text={MENU_SUBHEADER} />
            <MenuList menuItems={menuItems} />
          </Card>
        </div>
        <div className={styles.selectedItems}>
          <Card>
            <Header level={3} text={SELECTED_ITEMS_SUBHEADER} />
          </Card>
        </div>
      </div>
    </PageContainer>
  );
}
